name: Build & Deploy Perplexica Frontend
on:
  push:
    branches:
      - master

env:
  DUPLO_HOST: https://sully.duplocloud.net
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  DUPLO_TENANT: ksa-dev01
  CLOUD_CREDENTIALS: ${{ secrets.WORKFLOW_SERVICE_ACCOUNT }}
  CLOUD_ACCOUNT: sullyai-nonprod-ksa
  ARTIFACT_REGISTRY: me-central2-docker.pkg.dev/sullyai-nonprod-ksa/perplexica/frontend
  SERVICE_NAME_FRONTEND: perplexica-frontend

jobs:
  build-and-deploy-frontend:
    name: Build and Deplo Frontend Service 
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Duplo Setup
        uses: duplocloud/actions@main
        with:
          account-id: ${{ env.CLOUD_ACCOUNT }}
          credentials: ${{ env.CLOUD_CREDENTIALS }}

      - name: Set Version for the Service
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY }}

      - name: Build and Push Docker Image
        id: build_image
        uses: duplocloud/actions/build-image@3c4899bad07d3c7b34e46888056fa8d7d28b73fd
        with:
          registry: ${{ env.ARTIFACT_REGISTRY }}
          repo: perplexica-frontend
          dockerfile: app.dockerfile
          tag-strategy: DATE
          tags: ${{ env.DUPLO_TENANT }}-${{ env.SHORT_SHA }}
          push: true
          cache: true
          extra-args: >
            --build-arg BUILD_COMMIT=${{ env.SHORT_SHA }}
            --build-arg SERVICE_NAME=${{ env.SERVICE_NAME_FRONTEND }}

      # - name: Update Service in Duplo
      #   uses: duplocloud/actions/update-image@main
      #   with:
      #     type: service
      #     name: ${{ env.SERVICE_NAME_FRONTEND }}
      #     image: ${{ steps.build_image.outputs.image }}:${{ env.DUPLO_TENANT }}-${{ env.SHORT_SHA }}
