name: Build & Deploy Perplexica Backend
run-name: Build & Deploy ${{ github.event.inputs.tenant_name }} Backend
on:
  workflow_dispatch:
    inputs:
      tenant_name:
        description: 'Target DuploCloud tenant'
        required: true
        default: 'dev01'
        type: choice
        options:
          - dev01
          - prod
          - ksa-prod

env:
  DUPLO_HOST: https://sully.duplocloud.net
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  DUPLO_TENANT: ${{ inputs.tenant_name }}
  CLOUD_CREDENTIALS: ${{ secrets.WORKFLOW_SERVICE_ACCOUNT }}
  CLOUD_ACCOUNT: ${{ vars.CLOUD_ACCOUNT }}
  ARTIFACT_REGISTRY: ${{ vars.ARTIFACT_REGISTRY }}
  SERVICE_NAME_BACKEND: perplexica-backend

jobs:
  build-and-deploy-backend:
    name: Build and Deploy Backend Service 
    runs-on: ubuntu-latest
    environment: ${{ inputs.tenant_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Duplo Setup
        uses: duplocloud/actions@main
        with:
          account-id: ${{ env.CLOUD_ACCOUNT }}
          credentials: ${{ env.CLOUD_CREDENTIALS }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build and Push Docker Image
        id: build_image
        uses: duplocloud/actions/build-image@3c4899bad07d3c7b34e46888056fa8d7d28b73fd
        with:
          registry: ${{ env.ARTIFACT_REGISTRY }}
          repo: perplexica-backend
          dockerfile: backend.dockerfile
          tag-strategy: DATE
          tags: ${{ env.DUPLO_TENANT }}-${{ env.SHORT_SHA }}
          push: true
          cache: true

      - name: Update Service in Duplo
        uses: duplocloud/actions/update-image@main
        with:
          type: service
          name: ${{ env.SERVICE_NAME_BACKEND }}
          # image: ${{ steps.build_image.outputs.image }}:${{ env.DUPLO_TENANT }}-${{ env.SHORT_SHA }}
          image: ${{ steps.build_image.outputs.uri }}
